config/routes.rb
SampleApp::Application.routes.draw do

  get '/hashtags/:id/show', to: 'hashtags#show' , as: 'hashtag'
  # get '/search', to:'users#search', as:'search_user'
  # get '/qresults', to:'users#qresults', as:'query_user'
  get '/hashtags', to: 'hashtags#index'
  get "relationships/create"
  get "relationships/destroy"
  root 'static_pages#home'
  
  resources :users do

     member do
        get :following, :followers
      end

  end


  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "sendemail" => "static_pages#sendemail"
  get "help" => "static_pages#help"
  get "terms" => "static_pages#terms"
  get "signup" => "users#new"
  get "signin" => "sessions#new"
  delete "signout" => "sessions#destroy"
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :microposts

	self.per_page = 25
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :micropost_build

  def show
  	 @hashtag = Hashtag.find(params[:id])
  	 @microposts = @hashtag.microposts.paginate(page: params[:page])
  end

  def index
  	#@hashtags = Hashtag.all
    if params[:name].nil? || params[:name].empty?
      @hashtags = Hashtag.paginate(page: params[:page])
    else
      term = "%#{params[:name]}%"
      @hashtags = Hashtag.where("lower(name) like ?", term.downcase).paginate(page: params[:page])
    end
  end

  def search
  	@results = Hashtag.where(['name like ?', params[:tag] + '%']).limit(10)
  end


  private

    def micropost_build
        # Just for the modal
        @micropost ||= current_user.microposts.build
    end

end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<%= form_tag('/hashtags', method: :get) do %>
	            <div class="input-group custom-search-form">
	                <input type="text" name="name" id="name" class="form-control" placeholder="Search hashtag">
	                  <span class="input-group-btn">
		                <button class="btn btn-default" data-toggle="tooltip" data-placement="top" title="single Hashtag" type="submit">
		              	<span class="glyphicon glyphicon-search" ></span>
		              </button>
		              <button class="btn btn-default" data-toggle="tooltip" data-placement="top" title="All Hashtags" type="submit">
		              	<span class="glyphicon glyphicon-th-list"></span>
		              </button>
		            </span>
	            </div><!-- /input-group -->
            <% end %>
        </div>
	</div>
</div>
<p></p>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div>
				<% @hashtags.each do |tag| %>
					<hr/>
						<p class="text-info"><%= link_to tag.name, hashtag_path(tag) %></p>
					<hr/>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/hashtags/show.html.erb
<h1>Hashtags of <%= @hashtag.name %></h1>


<h3>Tweets (<%= @microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
<%= will_paginate @microposts %>