config/routes.rb
SampleApp::Application.routes.draw do

  get '/hashtags/:id/show', to: 'hashtags#show' , as: 'hashtag'
  # get '/search', to:'users#search', as:'search_user'
  # get '/qresults', to:'users#qresults', as:'query_user'
  get '/hashtags', to: 'hashtags#index'
  get "relationships/create"
  get "relationships/destroy"
  root 'static_pages#home'
  
  resources :users do

     member do
        get :following, :followers
      end

  end


  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "sendemail" => "static_pages#sendemail"
  get "help" => "static_pages#help"
  get "terms" => "static_pages#terms"
  get "signup" => "users#new"
  get "signin" => "sessions#new"
  delete "signout" => "sessions#destroy"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://twitter.com/Pranava_swaroop">&copy; 2014 Twitter, Inc.</a>
    by Pranava Swaroop
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Terms and Conditions", terms_path %></li>
    </ul>
  </nav>
</footer>
<script type="text/javascript">
  

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-47866999-2']);
  _gaq.push(['_setDomainName', 'wditwitter.herokuapp.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <nav class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><%= image_tag  "twitter.png", size: '30x30' %></a>
            <p class="small" style="color:#fff"><a href="#"></a></p>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">

             <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
             
             
             <% if signed_in? %>
              
              <li><%= link_to "Users", users_path %></li>

             <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span></a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "Profile", current_user %></li>
                     <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                     <li><%= link_to "Hashtags", hashtags_path %></li>
                     <li class="divider"></li>
                     <li>  <%= link_to "Sign out", signout_path, method: "delete" %> </li>
                    
                 </ul>
              </li>
              <li>
                <a data-toggle="modal" data-target="#myModal">
                  <span class="glyphicon glyphicon-comment"></span>
                </a>
              </li>
              <% else %>
                <li><%= link_to "Have an account?", signup_path %></li>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
          </ul>
          </div>
    </nav>
</div>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9] 
 <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<! [endif] -->

app/views/layouts/_tweetmod.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel" style="text-align:center">Tweet</h4>
      </div>
      <div class="modal-body">
        <section>
          <%= render 'shared/micropost_form' %>
        </section>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="https://about.twitter.com/sites/about/themes/gazebo_about/favicon.ico" type="image/vnd.microsoft.icon">
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header'%>


  <div class="container">
    <div class="row">
  	<% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "well text-info") %>
        <% end %>
  	<%= yield %>
    <% if signed_in? %>
      <%= render 'layouts/tweetmod' %>
    <% end %>
  	
    </div>
  </div>
  
  <div class="container" >
    <%= render 'layouts/footer'%>
  </div>
</body>
</html>